### PR TITLE
More flexible recurring events beyond weekly recurrence

### PR DESCRIPTION
**Pull request by Jethril**
Fixes issue #22.

### CODE REVIEW

**Comment by Jethril** [comment]
Currently working on the UI.
I will create a basic GUI because PR #113 will require to change it (if merged).

**Comment by Jethril** [comment]
Progression update (currently without CSS) so you can see the fields:
image

**Comment by Elkellympia** [comment]
> Progression update (currently without CSS) so you can see the fields: image

would it be possible to go higher than 1 year? i.e things like world cups are 4 years apart each other, so the 1 year would not be useful for that, maybe we could use something like regex or some option like that for advanced users. I have many many cool ideas like these for better integration with other stuff

i would really like to help you on this, unfortunately I'm not understanding the  code for me to work on it

**Comment by Jethril** [comment]
> would it be possible to go higher than 1 year? i.e things like world cups are 4 years apart each other, so the 1 year would not be useful for that, maybe we could use something like regex or some option like that for advanced users. I have many many cool ideas like these for better integration with other stuff

The UI is quite ugly for now but you can see "on a week basis ans every 1 week". If you select "on a year basis" you can set it to "every x years".
Would that solve your problem? Or do you meant, for example, every monday **and** every two years?

**Comment by Elkellympia** [comment]
> > would it be possible to go higher than 1 year? i.e things like world cups are 4 years apart each other, so the 1 year would not be useful for that, maybe we could use something like regex or some option like that for advanced users. I have many many cool ideas like these for better integration with other stuff
> 
> The UI is quite ugly for now but you can see "on a week basis" and "every 1 week". If you select "on a year basis" you can set it to "every x years". Would that solve your problem? Or do you meant, for example, every monday **and** every two years?

i was referring to that exactly, events that happen every 2 years or more.

**Comment by Jethril** [comment]
Well, it would require a tricky UI, like this one: https://crontab-generator.org/.
A good point is that the UI would allow to cover the full rrule specification.

What I could propose is to make this MR work as I imagined it, then enhance it (maybe with one more issue?).
@davish what's your opinion on this?

**Comment by davish** [comment]
Hi @Jethril, sorry for the radio silence, I've been heads-down on PR #303 that just got merged. Unfortunately, #303 rewrote must of the plugin, so this PR is no longer compatible with the architecture of the code. The good news is that for `rrule` was added as part of #303, so the only work remaining for issue #22 is the GUI. Thank you for your contribution!

**Comment by davish** [comment]
@Elkellympia, a good place to start would be the architecture guide that was just committed: https://github.com/davish/obsidian-full-calendar/blob/main/src/README.md

**Comment by hycday** [comment]
every issue that talk about an enhanced recurring feature leads to either a solution using an external online calendar... or to this issue's conclusion here.. or to https://github.com/davish/obsidian-full-calendar/pull/303 

as i'm not sure to understand the state of that one or the #303, i'm wondering what is the status or latest update please ?

**Pull request closed without merging**
