### PR TITLE
Feature - Remote Notes!

### PR DESCRIPTION
**Pull request by firststef**
### Notes for remote events

What if you were at a lecture and you need to write some details while also having a time reference? Doesn't it just feel terrible to not have notes for all your calendar events?

Well now you can! REMOTE REPLACE EVENTS
Enter notes immediately and start writing. Your events will also have a special symbol [N] that shows that this event is actually copied from remote!

remote-note

What other things:
- names for remote calendars! untill now, you could only see the url and color of a remote source, but now you can also have a name!

image

- no more: "You cannot edit this event" prompt - it was so frustrating!
- replaced special characters in events with _
- instant transition to the note (because this implementation does not hold some sort of cache or index, the naming convention cannot be changed for files, as such, it is only natural that I open the file instead of prompting for open)
- sorry for messy code, i'm not sure how I should've write things better but I can change stuff if you give me some advice

### CODE REVIEW

**Comment by firststef** [comment]
@davish please review, currently no formatter is available for remote events and it would be really useful to connect events on your calendar with your notes in this way.

**Comment by emmertex** [comment]
Well this is the missing feature to make this plugin great(useable)!
Any intention of adding this in, or do you intend to maintain your fork @firststef ?

**Comment by firststef** [comment]
@emmertex Thanks, well I would have loved to add it to the plugin but @davish doesn't seem to respond, I was thinking of doing a merge into my branch but I might not have time to do it right now, if you need I could let you know.

**Comment by davish** [comment]
Hi @emmertex and @firststef, sorry for not having responded to this PR. For the past few months I've been working on a big refactor of the plugin started in #204 and which will be finished in #303. It'll remove all the `models` that this PR relies on, and so unfortunately I don't think this PR will be a good fit for merging. The good news is that this feature will be much,  easier to implement efficiently in the new system.

**Comment by firststef** [comment]
ok, i'll close this then

**Pull request closed without merging**
